# Generated by Django 6.0.4 on 2026-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commune_village_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/photos/'),
        ),
    ]
